import { products as p1 } from './data1';
import { products2 as p2 } from './data2';
import { Product } from './types';

export const products: Product[] = [...p1, ...p2];

export const translations: Record<string, Record<string, any>> = {
  en: {
    logoTitle: '<strong>LED</strong> Product Selector',
    contactBtn: "&#9993;&ensp;If you can't find what you need, click here",
    compareBtn: '&#9878;&ensp;Compare&ensp;',
    catLabel: 'Category', colourTempLabel: 'Colour Temp', ledWidthLabel: 'LED Width',
    moduleTypeLabel: 'Module Type', voltageLabel: 'Voltage', ipRatingLabel: 'IP Rating',
    powerLabel: 'Power (W/m)', criLabel: 'CRI', clearAll: '&#10005; Clear all filters',
    sortAZ: 'A — Z', sortZA: 'Z — A', sortAvailability: 'Availability', sortPower: 'Power Rating', sortColour: 'Colour',
    searchPlaceholder: 'Search by spec or keyword — e.g. "24V warm white IP67" or "outdoor COB 3000K"',
    noResults: 'No matching products', noResultsSub: 'Try broadening your search or adjusting filters',
    stocked: 'Stocked', outOfStock: 'Out of Stock', viewStore: 'View Store &#8599;', buyNow: 'Buy Now', datasheet: 'Datasheet',
    addCmp: 'Add to comparison', removeCmp: 'Remove from comparison',
    inCompare: '✓ In Compare', plusCompare: '＋ Compare',
    compareBtnTitle: '&#9878; Side-by-Side Comparison',
    maxCompare: 'Maximum 5 products for comparison.',
    minCompare: 'Select at least 2 products to compare.',
    removeLbl: '✕ Remove',
    specCategory: 'Category', specVoltage: 'Voltage', specCCT: 'Colour Temp',
    specIP: 'IP Rating', specPower: 'Power', specLumens: 'Lumens', specCRI: 'CRI',
    specBeam: 'Beam Angle', specDimensions: 'Dimensions', specLedWidth: 'LED Width',
    specModuleType: 'Module Type',
    cmpProductName: 'Product Name', cmpSKU: 'SKU', cmpCategory: 'Category',
    cmpVoltage: 'Voltage', cmpCCT: 'Colour Temperature', cmpIP: 'IP Rating',
    cmpLedWidth: 'LED Width', cmpPower: 'Power (W/m)', cmpTotalPower: 'Total Power',
    cmpLumens: 'Luminous Output', cmpCRI: 'CRI', cmpBeam: 'Beam Angle',
    cmpDimensions: 'Dimensions', cmpAvailability: 'Availability',
    showingLabel: 'Showing', ofLabel: 'of',
    contactModalTitle: '&#9993; Special Orders &amp; Enquiries',
    contactTagline: "Can't find what you need in our catalogue? Our Special Product Team handles custom specifications, project quotations, and sourcing requests that fall outside our standard range.",
    usecases: [
      ['🔍', 'Product not listed in our catalogue'],
      ['📐', 'Non-standard dimensions or specifications'],
      ['💡', 'Large quantity or project bulk pricing'],
      ['🎨', 'Custom colour temperature or CRI'],
      ['🌍', 'Import / sourcing from specific manufacturers'],
      ['📋', 'OEM branding or packaging requirements'],
    ],
    whatToIncludeTitle: 'WHAT TO INCLUDE IN YOUR ENQUIRY',
    checklistItems: [
      'Product type or closest matching SKU',
      'Required specifications (voltage, power, CCT, IP rating)',
      'Quantity needed',
      'Project application or intended use',
      'Preferred delivery timeline',
    ],
    orReachUs: 'OR REACH US DIRECTLY',
    contactEmailLabel: 'Email', contactPhoneLabel: 'Phone', contactAddressLabel: 'Address',
    contactEmailCTA: '&#9993; Email Our Special Product Team',
    itemsSelectedForCompare: 'items selected for comparison',
    selectItemsToCompare: 'Select items to compare',
    resetCompare: 'Reset',
  },
  zh: {
    logoTitle: '<strong>LED</strong> 产品选择器',
    contactBtn: '&#9993;&ensp;如果找不到你要的产品，可以点这里',
    compareBtn: '&#9878;&ensp;对比&ensp;',
    catLabel: '产品类别', colourTempLabel: '色温', ledWidthLabel: 'LED 宽度',
    moduleTypeLabel: '模块类型', voltageLabel: '电压', ipRatingLabel: '防水等级',
    powerLabel: '功率 (W/m)', criLabel: '显色指数', clearAll: '&#10005; 清除所有筛选',
    sortAZ: 'A — Z', sortZA: 'Z — A', sortAvailability: '库存状态', sortPower: '功率排序', sortColour: '色温排序',
    searchPlaceholder: '按规格或关键词搜索，例如：24V 暖白 IP67',
    noResults: '没有匹配的产品', noResultsSub: '请尝试扩大搜索范围或调整筛选条件',
    stocked: '有库存', outOfStock: '缺货', viewStore: '查看详情 ↗', buyNow: '立即购买', datasheet: '数据表',
    addCmp: '加入对比', removeCmp: '从对比中移除',
    inCompare: '✓ 已加入对比', plusCompare: '＋ 加入对比',
    compareBtnTitle: '&#9878; 产品对比',
    maxCompare: '最多可对比5个产品。',
    minCompare: '请至少选择2个产品进行对比。',
    removeLbl: '✕ 移除',
    specCategory: '类别', specVoltage: '电压', specCCT: '色温',
    specIP: '防水等级', specPower: '功率', specLumens: '光通量', specCRI: '显色指数',
    specBeam: '光束角', specDimensions: '尺寸', specLedWidth: 'LED 宽度',
    specModuleType: '模块类型',
    cmpProductName: '产品名称', cmpSKU: '产品编码', cmpCategory: '类别',
    cmpVoltage: '电压', cmpCCT: '色温', cmpIP: '防水等级',
    cmpLedWidth: 'LED 宽度', cmpPower: '功率 (W/m)', cmpTotalPower: '总功率',
    cmpLumens: '光通量', cmpCRI: '显色指数', cmpBeam: '光束角',
    cmpDimensions: '尺寸', cmpAvailability: '库存',
    showingLabel: '显示', ofLabel: '共',
    contactModalTitle: '&#9993; 特殊订单与询价',
    contactTagline: '在我们的产品目录中找不到所需产品？我们的特殊产品团队可以处理超出标准范围的定制规格、项目报价和采购需求。',
    usecases: [
      ['🔍', '目录中未列出的产品'],
      ['📐', '非标准尺寸或规格'],
      ['💡', '大批量或项目批量定价'],
      ['🎨', '定制色温或显色指数'],
      ['🌍', '从特定制造商进口/采购'],
      ['📋', 'OEM 品牌或包装要求'],
    ],
    whatToIncludeTitle: '询价时请包含以下信息',
    checklistItems: [
      '产品类型或最接近的 SKU 编码',
      '所需规格（电压、功率、色温、防水等级）',
      '所需数量',
      '项目应用或预期用途',
      '首选交货时间',
    ],
    orReachUs: '或直接联系我们',
    contactEmailLabel: '电子邮件', contactPhoneLabel: '电话', contactAddressLabel: '地址',
    contactEmailCTA: '&#9993; 发邮件给特殊产品团队',
    itemsSelectedForCompare: '个产品已选择对比',
    selectItemsToCompare: '选择产品进行对比',
    resetCompare: '重置',
  },
  ja: {
    logoTitle: '<strong>LED</strong> 製品セレクター',
    contactBtn: '&#9993;&ensp;お探しの製品が見つからない場合はこちら',
    compareBtn: '&#9878;&ensp;比較&ensp;',
    catLabel: '製品カテゴリ', colourTempLabel: '色温度', ledWidthLabel: 'LED 幅',
    moduleTypeLabel: 'モジュールタイプ', voltageLabel: '電圧', ipRatingLabel: 'IP 等級',
    powerLabel: '消費電力 (W/m)', criLabel: '演色性', clearAll: '&#10005; 絞り込みをすべて解除',
    sortAZ: 'A — Z', sortZA: 'Z — A', sortAvailability: '在庫状況', sortPower: '電力順', sortColour: '色温順',
    searchPlaceholder: '仕様やキーワードで検索（例：24V 電球色 IP67）',
    noResults: '一致する製品が見つかりません', noResultsSub: '検索条件を広げるか絞り込み条件を調整してください',
    stocked: '在庫あり', outOfStock: '在庫切れ', viewStore: '詳細を見る ↗', buyNow: '今すぐ購入', datasheet: 'データシート',
    addCmp: '比較に追加', removeCmp: '比較から削除',
    inCompare: '✓ 比較中', plusCompare: '＋ 比較',
    compareBtnTitle: '&#9878; 製品比較',
    maxCompare: '比較できるのは最大5製品です。',
    minCompare: '2製品以上を選択して比較してください。',
    removeLbl: '✕ 削除',
    specCategory: 'カテゴリ', specVoltage: '電圧', specCCT: '色温度',
    specIP: 'IP 等級', specPower: '消費電力', specLumens: '光束', specCRI: '演色性',
    specBeam: 'ビーム角', specDimensions: '寸法', specLedWidth: 'LED 幅',
    specModuleType: 'モジュールタイプ',
    cmpProductName: '製品名', cmpSKU: 'SKU', cmpCategory: 'カテゴリ',
    cmpVoltage: '電圧', cmpCCT: '色温度', cmpIP: 'IP 等級',
    cmpLedWidth: 'LED 幅', cmpPower: '消費電力 (W/m)', cmpTotalPower: '総消費電力',
    cmpLumens: '光束出力', cmpCRI: '演色性', cmpBeam: 'ビーム角',
    cmpDimensions: '寸法', cmpAvailability: '在庫状況',
    showingLabel: '表示中', ofLabel: '/',
    contactModalTitle: '&#9993; 特別注文・お問い合わせ',
    contactTagline: 'カタログにお探しの製品がありませんか？私たちの特殊製品チームは、標準的な範囲外のカスタム仕様、プロジェクト見積もり、調達リクエストに対応しています。',
    usecases: [
      ['🔍', 'カタログに記載されていない製品'],
      ['📐', '非標準の寸法または仕様'],
      ['💡', '大量注文またはプロジェクト一括価格'],
      ['🎨', 'カスタム色温度またはCRI'],
      ['🌍', '特定メーカーからの輸入・調達'],
      ['📋', 'OEMブランディングまたはパッケージ要件'],
    ],
    whatToIncludeTitle: 'お問い合わせ時にご記入ください',
    checklistItems: [
      '製品タイプまたは最も近いSKU',
      '必要な仕様（電圧、消費電力、色温度、IP等級）',
      '必要数量',
      'プロジェクトの用途または目的',
      '希望納期',
    ],
    orReachUs: '直接お問い合わせ',
    contactEmailLabel: 'メール', contactPhoneLabel: '電話', contactAddressLabel: '住所',
    contactEmailCTA: '&#9993; 特殊製品チームへメールを送る',
    itemsSelectedForCompare: '個の製品が比較用に選択されました',
    selectItemsToCompare: '比較する製品を選択してください',
    resetCompare: 'リセット',
  },
  hi: {
    logoTitle: '<strong>LED</strong> उत्पाद चयनकर्ता',
    contactBtn: '&#9993;&ensp;यदि उत्पाद न मिले तो यहाँ क्लिक करें',
    compareBtn: '&#9878;&ensp;तुलना&ensp;',
    catLabel: 'श्रेणी', colourTempLabel: 'रंग तापमान', ledWidthLabel: 'LED चौड़ाई',
    moduleTypeLabel: 'मॉड्यूल प्रकार', voltageLabel: 'वोल्टेज', ipRatingLabel: 'IP रेटिंग',
    powerLabel: 'शक्ति (W/m)', criLabel: 'CRI', clearAll: '&#10005; सभी फ़िल्टर हटाएं',
    sortAZ: 'A — Z', sortZA: 'Z — A', sortAvailability: 'उपलब्धता', sortPower: 'पावर रेटिंग', sortColour: 'रंग तापमान',
    searchPlaceholder: 'विशेषता या कीवर्ड से खोजें...',
    noResults: 'कोई उत्पाद नहीं मिला', noResultsSub: 'खोज को व्यापक बनाएं या फ़िल्टर बदलें',
    stocked: 'उपलब्ध', outOfStock: 'स्टॉक में नहीं', viewStore: 'स्टोर देखें ↗', buyNow: 'अभी खरीदें', datasheet: 'डेटाशीट',
    addCmp: 'तुलना में जोड़ें', removeCmp: 'तुलना से हटाएं',
    inCompare: '✓ तुलना में', plusCompare: '＋ तुलना',
    compareBtnTitle: '&#9878; तुलना',
    maxCompare: 'अधिकतम 5 उत्पादों की तुलना की जा सकती है।',
    minCompare: 'तुलना के लिए कम से कम 2 उत्पाद चुनें।',
    removeLbl: '✕ हटाएं',
    specCategory: 'श्रेणी', specVoltage: 'वोल्टेज', specCCT: 'रंग तापमान',
    specIP: 'IP रेटिंग', specPower: 'शक्ति', specLumens: 'ल्यूमेन', specCRI: 'CRI',
    specBeam: 'बीम कोण', specDimensions: 'आयाम', specLedWidth: 'LED चौड़ाई',
    specModuleType: 'मॉड्यूल प्रकार',
    cmpProductName: 'उत्पाद का नाम', cmpSKU: 'SKU', cmpCategory: 'श्रेणी',
    cmpVoltage: 'वोल्टेज', cmpCCT: 'रंग तापमान', cmpIP: 'IP रेटिंग',
    cmpLedWidth: 'LED चौड़ाई', cmpPower: 'शक्ति (W/m)', cmpTotalPower: 'कुल शक्ति',
    cmpLumens: 'प्रकाश उत्पादन', cmpCRI: 'CRI', cmpBeam: 'बीम कोण',
    cmpDimensions: 'आयाम', cmpAvailability: 'उपलब्धता',
    showingLabel: 'दिखा रहे हैं', ofLabel: 'में से',
    contactModalTitle: '&#9993; विशेष ऑर्डर और पूछताछ',
    contactTagline: 'हमारी सूची में आपका उत्पाद नहीं मिला? हमारी विशेष उत्पाद टीम मानक श्रेणी के बाहर कस्टम विशिष्टताओं, परियोजना उद्धरणों और सोर्सिंग अनुरोधों को संभालती है।',
    usecases: [
      ['🔍', 'हमारी सूची में नहीं है'],
      ['📐', 'गैर-मानक आयाम या विशिष्टताएं'],
      ['💡', 'बड़ी मात्रा या प्रोजेक्ट बल्क मूल्य'],
      ['🎨', 'कस्टम रंग तापमान या CRI'],
      ['🌍', 'विशिष्ट निर्माताओं से आयात/सोर्सिंग'],
      ['📋', 'OEM ब्रांडिंग या पैकेजिंग आवश्यकताएं'],
    ],
    whatToIncludeTitle: 'पूछताछ में शामिल करें',
    checklistItems: [
      'उत्पाद प्रकार या निकटतम SKU कोड',
      'आवश्यक विशिष्टताएं (वोल्टेज, शक्ति, रंग तापमान, IP रेटिंग)',
      'आवश्यक मात्रा',
      'परियोजना का उपयोग या उद्देश्य',
      'पसंदीदा डिलीवरी समयरेखा',
    ],
    orReachUs: 'सीधे संपर्क करें',
    contactEmailLabel: 'ईमेल', contactPhoneLabel: 'फ़ोन', contactAddressLabel: 'पता',
    contactEmailCTA: '&#9993; विशेष उत्पाद टीम को ईमेल करें',
    itemsSelectedForCompare: 'तुलना के लिए चुने गए आइटम',
    selectItemsToCompare: 'तुलना करने के लिए आइटम चुनें',
    resetCompare: 'रीसेट',
  },
  vi: {
    logoTitle: '<strong>LED</strong> Bộ Chọn Sản Phẩm',
    contactBtn: '&#9993;&ensp;Không tìm thấy sản phẩm? Nhấn vào đây',
    compareBtn: '&#9878;&ensp;So sánh&ensp;',
    catLabel: 'Danh mục', colourTempLabel: 'Nhiệt độ màu', ledWidthLabel: 'Độ rộng LED',
    moduleTypeLabel: 'Loại module', voltageLabel: 'Điện áp', ipRatingLabel: 'Chỉ số IP',
    powerLabel: 'Công suất (W/m)', criLabel: 'CRI', clearAll: '&#10005; Xóa tất cả bộ lọc',
    sortAZ: 'A — Z', sortZA: 'Z — A', sortAvailability: 'Tình trạng kho', sortPower: 'Công suất', sortColour: 'Màu sắc',
    searchPlaceholder: 'Tìm kiếm theo thông số hoặc từ khóa...',
    noResults: 'Không tìm thấy sản phẩm phù hợp', noResultsSub: 'Hãy mở rộng tìm kiếm hoặc điều chỉnh bộ lọc',
    stocked: 'Còn hàng', outOfStock: 'Hết hàng', viewStore: 'Xem cửa hàng ↗', buyNow: 'Mua ngay', datasheet: 'Tài liệu kỹ thuật',
    addCmp: 'Thêm vào so sánh', removeCmp: 'Xóa khỏi so sánh',
    inCompare: '✓ Đang so sánh', plusCompare: '＋ So sánh',
    compareBtnTitle: '&#9878; So sánh sản phẩm',
    maxCompare: 'Tối đa 5 sản phẩm để so sánh.',
    minCompare: 'Chọn ít nhất 2 sản phẩm để so sánh.',
    removeLbl: '✕ Xóa',
    specCategory: 'Danh mục', specVoltage: 'Điện áp', specCCT: 'Nhiệt độ màu',
    specIP: 'Chỉ số IP', specPower: 'Công suất', specLumens: 'Quang thông', specCRI: 'CRI',
    specBeam: 'Góc chiếu', specDimensions: 'Kích thước', specLedWidth: 'Độ rộng LED',
    specModuleType: 'Loại module',
    cmpProductName: 'Tên sản phẩm', cmpSKU: 'Mã sản phẩm', cmpCategory: 'Danh mục',
    cmpVoltage: 'Điện áp', cmpCCT: 'Nhiệt độ màu', cmpIP: 'Chỉ số IP',
    cmpLedWidth: 'Độ rộng LED', cmpPower: 'Công suất (W/m)', cmpTotalPower: 'Tổng công suất',
    cmpLumens: 'Quang thông', cmpCRI: 'CRI', cmpBeam: 'Góc chiếu',
    cmpDimensions: 'Kích thước', cmpAvailability: 'Tình trạng',
    showingLabel: 'Hiển thị', ofLabel: 'trong số',
    contactModalTitle: '&#9993; Đặt hàng đặc biệt &amp; Yêu cầu tư vấn',
    contactTagline: 'Không tìm thấy sản phẩm trong danh mục? Đội ngũ sản phẩm đặc biệt của chúng tôi xử lý các thông số kỹ thuật tùy chỉnh, báo giá dự án và yêu cầu tìm nguồn cung ứng ngoài phạm vi tiêu chuẩn.',
    usecases: [
      ['🔍', 'Sản phẩm chưa có trong danh mục'],
      ['📐', 'Kích thước hoặc thông số phi tiêu chuẩn'],
      ['💡', 'Số lượng lớn hoặc giá dự án'],
      ['🎨', 'Nhiệt độ màu hoặc CRI tùy chỉnh'],
      ['🌍', 'Nhập khẩu / nguồn cung từ nhà sản xuất cụ thể'],
      ['📋', 'Yêu cầu OEM hoặc đóng gói riêng'],
    ],
    whatToIncludeTitle: 'THÔNG TIN CẦN CUNG CẤP',
    checklistItems: [
      'Loại sản phẩm hoặc SKU gần nhất',
      'Thông số kỹ thuật yêu cầu (điện áp, công suất, CCT, IP)',
      'Số lượng cần thiết',
      'Ứng dụng hoặc mục đích sử dụng',
      'Thời gian giao hàng mong muốn',
    ],
    orReachUs: 'HOẶC LIÊN HỆ TRỰC TIẾP',
    contactEmailLabel: 'Email', contactPhoneLabel: 'Điện thoại', contactAddressLabel: 'Địa chỉ',
    contactEmailCTA: '&#9993; Gửi email cho Đội sản phẩm đặc biệt',
    itemsSelectedForCompare: 'sản phẩm đã chọn để so sánh',
    selectItemsToCompare: 'Chọn sản phẩm để so sánh',
    resetCompare: 'Đặt lại',
  }
};
